R_OPTS=--vanilla --no-save

figures_tiff:
	nohup R CMD BATCH $(R_OPTS) 01-A-level-plot.R;\
	nohup R CMD BATCH $(R_OPTS) 01-B-level-plot-proportional.R;\
	nohup R CMD BATCH $(R_OPTS) 02-A-mosaic-plot.R;\
	nohup R CMD BATCH $(R_OPTS) 02-B-mosaic-plot.R;\
	nohup R CMD BATCH $(R_OPTS) 03-A-contour-plot.R;\
	nohup R CMD BATCH $(R_OPTS) 03-B-contour-plot-localreg.r;\
	nohup R CMD BATCH $(R_OPTS) 04-A-venn-diagram.R;\
	nohup R CMD BATCH $(R_OPTS) 04-B-venn-diagram-filled.R;\
	nohup R CMD BATCH $(R_OPTS) 04-C-venn-diagram-proportional.R;\
	nohup R CMD BATCH $(R_OPTS) 05-bar-chart.R;\
	nohup R CMD BATCH $(R_OPTS) 06-forest-plot.R;\
	nohup R CMD BATCH $(R_OPTS) 07-A-tree-plot.R;\
	nohup R CMD BATCH $(R_OPTS) 07-B-tree-plot.R;\
	nohup R CMD BATCH $(R_OPTS) 08-galbraith-plot.R;\
	nohup R CMD BATCH $(R_OPTS) 09-labbe-plot.R;\
	nohup R CMD BATCH $(R_OPTS) 10-stepp-plot.R;\
	nohup R CMD BATCH $(R_OPTS) 11-upsetR-plot.R;\
	nohup R CMD BATCH $(R_OPTS) 12-SubgroUpSetR-plot.R;\
	nohup R CMD BATCH $(R_OPTS) 13-circular-plot.R;\
	nohup R CMD BATCH $(R_OPTS) 14-mosaic-plot.R;\
	nohup R CMD BATCH $(R_OPTS) 15-nightingale-rose.R;\
	nohup R CMD BATCH $(R_OPTS) 16-nightingale-rose.R;\
	nohup R CMD BATCH $(R_OPTS) 17-alluvial-plot-surv.R;\
	nohup R CMD BATCH $(R_OPTS) 18-alluvial-plot.R;\
	nohup R CMD BATCH $(R_OPTS) 19-alt-a-plot.R;\
	nohup R CMD BATCH $(R_OPTS) 19-alt-b-plot.R;\
	nohup R CMD BATCH $(R_OPTS) 19-alt-c-plot.R;\
	nohup R CMD BATCH $(R_OPTS) 19-alt-d-plot.R;\
	nohup R CMD BATCH $(R_OPTS) 19-alt-e-plot.R;\
	nohup R CMD BATCH $(R_OPTS) 19-alt-f-plot.R;\
	nohup R CMD BATCH $(R_OPTS) 21-circle-matrix.R;\
	nohup R CMD BATCH $(R_OPTS) 23-alt-a-matrix.R;

